<?php
echo "<head>";
echo "<title>Menu</title>";
echo "</head>";

echo "<body>";
echo "<center>";
echo "<h1>Menu</h1>";
echo "<br><br>";
echo "<a href='1_1.html'>Ejercicio 1</a>";
echo "<br><br>";
echo "<a href='2_1.html'>Ejercicio 2</a>";
echo "<br><br>";
echo "<a href='3_1.html'>Ejercicio 3</a>";
echo "<br><br>";
echo "<a href='4_1.html'>Ejercicio 4</a>";
echo "<br><br>";
echo "<a href='5_1.html'>Ejercicio 5</a>";
echo "<br><br>";
echo "<a href='6_1.html'>Ejercicio 6</a>";
echo "<br><br>";
echo "<a href='7_1.html'>Ejercicio 7</a>";
echo "<br><br>";
echo "<a href='8_1.html'>Ejercicio 8</a>";
echo "<br><br>";
echo "<a href='9_1.html'>Ejercicio 9</a>";
echo "<br><br>";
echo "<a href='10_1.html'>Ejercicio 10</a>";
echo "<br><br>";
echo "<a href='11_1.html'>Ejercicio 11</a>";
echo "<br><br>";
echo "<a href='12_1.html'>Ejercicio 12</a>";
echo "<br><br>";
echo "<a href='13_1.html'>Ejercicio 13</a>";
echo "<br><br>";
echo "<a href='14_1.html'>Ejercicio 14</a>";
echo "<br><br>";
echo "<a href='15_1.html'>Ejercicio 15</a>";
echo "<br><br>";
echo "<a href='16_1.html'>Ejercicio 16</a>";
echo "<br><br>";
echo "<a href='17_1.html'>Ejercicio 17</a>";
echo "<br><br>";
echo "<a href='18_1.html'>Ejercicio 18</a>";
echo "<br><br>";
echo "<a href='19_1.html'>Ejercicio 19</a>";
echo "<br><br>";
echo "<a href='20_1.html'>Ejercicio 20</a>";
echo "<br><br>";
echo "<a href='21_1.html'>Ejercicio 21</a>";
echo "<br><br>";
echo "<a href='22_1.html'>Ejercicio 22</a>";
echo "<br><br>";
echo "<a href='23_1.html'>Ejercicio 23</a>";
echo "<br><br>";
echo "<a href='24_1.html'>Ejercicio 24</a>";
echo "<br><br>";
echo "<a href='25_1.html'>Ejercicio 25</a>";
?>